### ISSUE TITLE
Public folder not being Recognized

### ISSUE THREAD

**Issue by JNishitha** [vvs-basanth/gaac-page-f#10]
I am currently experiencing issues with integrating images into the footer section due to the inability to import them from the public folder.
I attempted to import the images using "@/public" and "../../public", but encountered a problem with the public folder not being recognized. I asked Ibrahim, who recommended adding the respective code to tailwind.config.ts, yet the issue persisted.

**Code:-**
const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    './public/**/*.{jpg,jpeg,png,webp,svg}',
  ],

**Comment by vvs-basanth** [comment]
Please update the issue and let me know if we can close the issue or not.
