### ISSUE TITLE
Change favicon.ico to GAAC logo

### ISSUE THREAD

**Issue by IbrahimDev00** [vvs-basanth/gaac-page-f#14]
**Favicon** - Favicons are displayed on tabs at the top of a web browser.

Using the GAAC logo over here would allow for more visibility of the Club's website

GAAC logo - 
![enhanced_gaac_logo](https://github.com/vvs-basanth/gaac-page-f/assets/147825977/5d6ac8c5-0d59-4066-acde-748454cc9128)

**Comment by vvs-basanth** [comment]
Are the changes done?
Any update on this?

**Comment by IbrahimDev00** [comment]
i will create a PR for everything at once

**Comment by IbrahimDev00** [comment]
Added favicon.ico, in latest PR #16
